[package]
name = "discloud-desktop"
version = "0.0.1"
description = "DisCloud desktop client"
authors = ["Nguyen Mau Minh"]
edition = "2021"
license = "MIT"
repository = "https://github.com/mewisme/discloud"

[lib]
name = "discloud_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
