"use client"

import { Loader2Icon, RefreshCwIcon } from "lucide-react"
import { QRCodeSVG } from "qrcode.react"
import { Controller, type UseFormReturn } from "react-hook-form"

import { DateTime } from "@/components/common/date-time"
import { Button } from "@/components/ui/button"
import { Field, FieldDescription, FieldError, FieldLabel } from "@/components/ui/field"
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp"
import type { MFAEnrollment as MFAEnrollmentModel } from "@/lib/api/models"

type TOTPValues = { code: string }

export function MFAEnrollment({
  enrollment,
  form,
  starting,
  onConfirm,
  onStartOver,
}: {
  enrollment: MFAEnrollmentModel
  form: UseFormReturn<TOTPValues>
  starting: boolean
  onConfirm: (values: TOTPValues) => Promise<void>
  onStartOver: () => Promise<void>
}) {
  const state = form.formState
  const secret = provisioningSecret(enrollment.provisioningUri)

  return (
    <form className="space-y-5" onSubmit={form.handleSubmit(onConfirm)}>
      <div className="grid gap-5 sm:grid-cols-[auto_1fr] sm:items-center">
        <div className="w-fit rounded-xl border bg-white p-3">
          <QRCodeSVG value={enrollment.provisioningUri} size={176} level="M" />
        </div>

        <div className="space-y-2 text-sm">
          <p className="font-medium">Scan this QR code with your authenticator app.</p>
          <p className="text-muted-foreground">Setup expires <DateTime value={enrollment.expiresAt} /></p>

          {secret && (
            <div className="space-y-1">
              <p className="text-xs text-muted-foreground">Manual setup key</p>
              <code className="block break-all rounded-lg bg-muted px-2.5 py-2 text-xs">{secret}</code>
            </div>
          )}
        </div>
      </div>

      <Field data-invalid={!!state.errors.code}>
        <FieldLabel>Authentication code</FieldLabel>
        <Controller
          control={form.control}
          name="code"
          render={({ field }) => (
            <InputOTP
              maxLength={6}
              inputMode="numeric"
              autoComplete="one-time-code"
              autoFocus
              disabled={state.isSubmitting}
              aria-invalid={!!state.errors.code}
              value={field.value}
              onChange={field.onChange}
            >
              <InputOTPGroup>
                {Array.from({ length: 6 }, (_, index) => <InputOTPSlot key={index} index={index} />)}
              </InputOTPGroup>
            </InputOTP>
          )}
        />
        <FieldDescription>Enter the 6-digit code generated by your authenticator.</FieldDescription>
        <FieldError errors={[state.errors.code]} />
      </Field>

      <div className="flex flex-wrap gap-2">
        <Button type="submit" disabled={state.isSubmitting}>
          {state.isSubmitting && <Loader2Icon className="animate-spin" />}
          {state.isSubmitting ? "Verifying…" : "Enable MFA"}
        </Button>

        <Button type="button" variant="outline" disabled={starting || state.isSubmitting} onClick={() => void onStartOver()}>
          {starting ? <Loader2Icon className="animate-spin" /> : <RefreshCwIcon />}
          Start over
        </Button>
      </div>
    </form>
  )
}

function provisioningSecret(uri: string) {
  try {
    return new URL(uri).searchParams.get("secret") ?? ""
  } catch {
    return ""
  }
}