*

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!web/
!web/**

!packages/
!packages/**

!scripts/
scripts/*
!scripts/sync-app-icons.cjs

!desktop/
desktop/*
!desktop/src-tauri/
desktop/src-tauri/*
!desktop/src-tauri/icons/
desktop/src-tauri/icons/*
!desktop/src-tauri/icons/icon.png
!desktop/src-tauri/icons/icon.ico

web/node_modules
web/.next
web/coverage
web/.env
web/.env.*

packages/**/node_modules
packages/**/dist